travis:
  secure:
    BINSTAR_TOKEN: jkh7Oxbe9GvBoFV27N9u8q6XhR1iRVJqbOF3lyS2GOWEfP0PdAOALRAJdRxzrpbxlJt6Fl85t5PFkvj1w5HocNu0Zv+Pfl4ydlJuyoIpOXSuOOzFqKsCf0GY0DalNfXN1q/uQs2oDfvgMkMWo7RCNQwXCR1O7Nz5b0Jvl8LINkB5pLvgN8IUrQHRg/Wu8r9nqS0p0c2A1lpVU/sXWkphluubpp7iCABBq/UybkK3XmsSuUjQFnIi/v/MIRX9o3yMiZ03DE7BuCjT6OhoNdLo6TzjfpqOgZNjXYOa+KYmG+cKjSPduO5TLa5neWsA5c+PyU5ossUS1gLSqD54EmTkBsDqkSyyc61anVLR+a0T/s7HKP5Tt9uVcGgAwigy1qIgFJI+IHjJxbx2nrxXr73D5cN2KG39FIZTAvJtzyGEarzxBa7uucQNqNff9A6Ab1ALPeApW7RSjzHLZ9vZJPIlSUa0e6AcvArBC2p+3BSqM7QDmuvfybrowI3hl2d3FZqf7h0L4UjbO9x/Im3XG1ibp58ztJlir5KI4K8pjR13u3zIw2tdGNLTQla2p086UnJ0BUBeAy06evWTR7r8z+mM2wx2l2zeC67Lrhh00SbydENSbQGAcwDu/TVY5zAxi1CAj1wELG643nS7wXgB1fvlh+wi/FrlAQgFm2JuaZGX6j0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
